align_method: "sift"            # Opções: sift, ecc, orb, none
stack_method: "laplacian"      # Opções: laplacian (Multiescala Wang), naive_log
pyr_depth: 5                   # Profundidade da pirâmide (5-7 ideal para imagens 4K+)
kernel_size: 5                 # Tamanho da matriz Gaussiana (deve ser número ímpar)
use_gpu: true                  # Envia operações de Warp e Filter2D via UMat para VRAM 
output_format: ".tiff"         # Tiff preserva faixa dinâmica sem perdas de compactação JPEG
max_features: 1000             # Limite estrito de vetores para algoritmos KAZE/SIFT
crop_align: true
reference_strategy: "middle" # "first", "middle", "last"
images_per_stack: 15